import { useState } from "react";
import { Copy, Check, Pencil, Eye, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "@/hooks/use-toast";

interface JustificationPreviewProps {
  justification: string;
  onChange: (text: string) => void;
  onGenerateAppeal: () => void;
  isGeneratingAppeal?: boolean;
}

export function JustificationPreview({
  justification,
  onChange,
  onGenerateAppeal,
  isGeneratingAppeal = false,
}: JustificationPreviewProps) {
  const [editing, setEditing] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(justification);
    setCopied(true);
    toast({ title: "Copied!", description: "Justification copied to clipboard." });
    setTimeout(() => setCopied(false), 2000);
  };

  const buildFileNameBase = () => {
    const stamp = new Date().toISOString().slice(0, 10);
    return `medical-necessity-justification-${stamp}`;
  };

  const handleDownloadDoc = () => {
    const header = "To Whom It May Concern\n\n";
    const footer = "\n\nGenerated by Hasting Apollo";
    const content = `${header}${justification}${footer}`;
    const blob = new Blob(["\ufeff", content], { type: "application/msword;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${buildFileNameBase()}.doc`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const margin = 48;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - margin * 2;
    const body = doc.splitTextToSize(justification, maxWidth);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text("To Whom It May Concern,", margin, 64);
    doc.text(body, margin, 88, { maxWidth, lineHeightFactor: 1.5 });
    doc.save(`${buildFileNameBase()}.pdf`);
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg font-heading">Medical Necessity Justification</CardTitle>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-xs text-muted-foreground">
              Draft — Not Submitted
            </Badge>
            <Button variant="ghost" size="sm" onClick={() => setEditing(!editing)}>
              {editing ? <Eye className="h-4 w-4" /> : <Pencil className="h-4 w-4" />}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {editing ? (
          <Textarea
            value={justification}
            onChange={(e) => onChange(e.target.value)}
            className="min-h-[250px] text-sm leading-relaxed font-body"
          />
        ) : (
          <div className="bg-secondary/50 rounded-lg p-4 text-sm leading-relaxed whitespace-pre-wrap font-body">
            {justification}
          </div>
        )}
        <Button onClick={handleCopy} className="w-full" variant={copied ? "secondary" : "default"}>
          {copied ? (
            <>
              <Check className="h-4 w-4 mr-2" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="h-4 w-4 mr-2" />
              Copy to Clipboard
            </>
          )}
        </Button>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          <Button variant="outline" onClick={handleDownloadPdf}>
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
          <Button variant="outline" onClick={handleDownloadDoc}>
            <Download className="h-4 w-4 mr-2" />
            Download DOC
          </Button>
        </div>
        <div className="rounded-lg border border-dashed p-3 bg-secondary/30">
          <p className="text-sm font-medium">If denied -&gt; Auto Appeal</p>
          <p className="text-xs text-muted-foreground mt-1">
            Generate an appeal draft that reframes evidence and directly addresses common denial reasons.
          </p>
          <Button variant="outline" size="sm" className="mt-3" onClick={onGenerateAppeal} disabled={isGeneratingAppeal}>
            {isGeneratingAppeal ? "Generating appeal..." : "Generate Appeal Draft"}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
